### ISSUE TITLE
Remove required for header and footer

### ISSUE THREAD

**Issue by jodymac** [jksevend/side_navigation#9]
request footer and header not be required.  Instead, optionally be able to place a container that we can then add our own widgets to both areas

**Comment by jksevend** [comment]
Did I understand correctly that instead of me providing the general layout of the footer and header widget it will be the end user who does it? 

I had planned to add modes to the bar. These modes decide whether you want a header or footer at all or just the normal bar.

**Comment by jodymac** [comment]
Yes.  In my particular case on this project, I don't need the header as implemented, nor the footer.  I may however decide to put the logo in the header area and nothing else.

**Comment by jksevend** [comment]
Ahh alright. So ive made some unreleased changes where the header and footer are optional (looks as before in v0.0.4 then).

Regarding making the Header a Abstract widget instead of a SideNavigationBarHeader, ive thought about this and it would give users the most flexibiliy but however then its also up to the user to handle what widget to show when the bar is expanded or not. I dont want that. 

Instead im thinking of implementing a factory Constructor for SideNavigationBarHeader which lets the user ONLY choose an image

**Comment by jodymac** [comment]
If it’s not a cause of having GitHub issues created because of what you allow, I would let the users have as much flexibility as possible.  I’m sure this plugin has already been altered well away from what you originally planned, but having a default behavior that we can at least override would be my vote.  Ie, the header and the footer, I just don’t need them for this project but that may change in my next version where I do want to do something with that space, but not what the plugin is dictating. 

 I think it would be great if out of the box the plugin handled the widget to show when the bar is expanded, but it would be much more valuable to me with the option to customize with my own widget(s) if I wanted to change that behavior.

**Comment by jksevend** [comment]
I agree with you. In case of the header there is not much Customizing until yet altough you can pass three widgets to it, it is me who decided where to put those and lay them out. 

This package is going really well. just stopped for about 3 to 4 months because of work. I had the header and footer planned back then already. 

But because of the Flutter native NavigationRail i thought nobody would use this anyways. But it in my opinion my package shines on desktop. Thats why i developed a menu like this in the first place locally in my project until i decided to make a package out of it. 

4 Months didnt look then 23 likes that was very motivating to me!

**Comment by jksevend** [comment]
I will keep this idea of passing a normal widget in my head and will try to find a way to make it work.

**Comment by jodymac** [comment]
Great!  I found your package after looking at the flutter default navigation rail and thought it was one of their rarely clunky solutions.  Your example sold me, with of course, what I already communicated with you.  Great job and thanks!

**Comment by jodymac** [comment]
Sorry for the clutter, but just saw you updated the package.  That’s head and shoulders above most for making changes!  Thank you.

**Comment by jksevend** [comment]
Yes i tried to implement most of the feedback and the theme was a personal thing of mine. just has to be present :)
